version: '3.8'

services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - "./default.sqlite3:/app/default.sqlite3"
